module.exports = {
    ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SERCER || 'SECRET',
    REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET || 'R_SECRET',

    ROOT_EMAIL: process.env.ROOT_EMAIL,
    ROOT_EMAIL_PASSW: process.env.ROOT_EMAIL_PASSW,
    ROOT_EMAIL_SERVICE: process.env.ROOT_EMAIL_SERVICE,

};
